name       : opus-tools
version    : 0.1.10
release    : 1
source     :
    - http://downloads.xiph.org/releases/opus/opus-tools-0.1.10.tar.gz : a2357532d19471b70666e0e0ec17d514246d8b3cb2eb168f68bb0f6fd372b28c
license    :
    - BSD-2-Clause
    - GPL-2.0
component  : multimedia.audio
summary    : Collection of tools for working with opus files
description: |
    Opus-tools is a collection of tools for working with opus files currently under development.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(ogg)
    - pkgconfig(opus)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
