name       : opus-tools
version    : 0.2
release    : 3
source     :
    - https://archive.mozilla.org/pub/opus/opus-tools-0.2.tar.gz : b4e56cb00d3e509acfba9a9b627ffd8273b876b4e2408642259f6da28fa0ff86
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
component  : multimedia.audio
summary    : Collection of tools for working with opus files
description: |
    Opus-tools is a collection of tools for working with opus files currently under development.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libopusenc)
    - pkgconfig(opusfile)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
